import React from 'react';

// Weekly Health Report Email Template Data
export interface WeeklyHealthReportData {
  petName: string;
  petPhoto?: string;
  weekStart: Date;
  weekEnd: Date;
  summary: {
    medicationCompliance: number;
    feedingCompliance: number;
    symptomsLogged: number;
    appointmentsAttended: number;
  };
  highlights: string[];
  concerns: string[];
  upcomingAppointments: Array<{
    date: Date;
    clinic: string;
    reason: string;
  }>;
  medicationsDue: Array<{
    name: string;
    dueDate: Date;
    refillNeeded: boolean;
  }>;
  aiInsights: string[];
}

// Email template component for preview
export const WeeklyHealthReportPreview: React.FC<WeeklyHealthReportData> = (data) => {
  const formatDate = (date: Date) => {
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  return (
    <div className="max-w-2xl mx-auto bg-white rounded-2xl shadow-lg overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-primary-500 to-primary-400 p-8 text-center">
        <h1 className="text-3xl font-bold text-white mb-2">🐾 Weekly Health Report</h1>
        <p className="text-white opacity-90">
          {formatDate(data.weekStart)} - {formatDate(data.weekEnd)}
        </p>
      </div>

      {/* Pet Info */}
      <div className="bg-primary-50 p-6 text-center border-b-2 border-primary-200">
        {data.petPhoto && (
          <img
            src={data.petPhoto}
            alt={data.petName}
            className="w-24 h-24 rounded-full object-cover border-4 border-white mx-auto mb-3"
          />
        )}
        <h2 className="text-2xl font-bold text-primary-900">{data.petName}</h2>
        <p className="text-primary-700">Your beloved companion</p>
      </div>

      {/* Summary Stats */}
      <div className="p-6">
        <h3 className="text-xl font-bold text-gray-900 mb-4">📊 This Week's Summary</h3>
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-green-50 p-4 rounded-xl border-2 border-green-200">
            <div className="text-3xl font-bold text-green-700">
              {data.summary.medicationCompliance}%
            </div>
            <div className="text-sm text-green-600">Medication Compliance</div>
          </div>
          <div className="bg-yellow-50 p-4 rounded-xl border-2 border-yellow-200">
            <div className="text-3xl font-bold text-yellow-700">
              {data.summary.feedingCompliance}%
            </div>
            <div className="text-sm text-yellow-600">Feeding Compliance</div>
          </div>
          <div className="bg-blue-50 p-4 rounded-xl border-2 border-blue-200">
            <div className="text-3xl font-bold text-blue-700">{data.summary.symptomsLogged}</div>
            <div className="text-sm text-blue-600">Symptoms Logged</div>
          </div>
          <div className="bg-pink-50 p-4 rounded-xl border-2 border-pink-200">
            <div className="text-3xl font-bold text-pink-700">
              {data.summary.appointmentsAttended}
            </div>
            <div className="text-sm text-pink-600">Appointments Attended</div>
          </div>
        </div>
      </div>

      {/* Highlights */}
      {data.highlights.length > 0 && (
        <div className="bg-green-50 p-6">
          <h3 className="text-xl font-bold text-green-800 mb-3">✨ Highlights</h3>
          <ul className="list-disc list-inside space-y-2 text-green-700">
            {data.highlights.map((highlight, index) => (
              <li key={index}>{highlight}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Concerns */}
      {data.concerns.length > 0 && (
        <div className="bg-red-50 p-6">
          <h3 className="text-xl font-bold text-red-800 mb-3">⚠️ Areas of Concern</h3>
          <ul className="list-disc list-inside space-y-2 text-red-700">
            {data.concerns.map((concern, index) => (
              <li key={index}>{concern}</li>
            ))}
          </ul>
        </div>
      )}

      {/* AI Insights */}
      {data.aiInsights.length > 0 && (
        <div className="bg-blue-50 p-6">
          <h3 className="text-xl font-bold text-blue-800 mb-3">🤖 AI Insights</h3>
          <div className="space-y-3 text-blue-700">
            {data.aiInsights.map((insight, index) => (
              <p key={index}>{insight}</p>
            ))}
          </div>
        </div>
      )}

      {/* Footer */}
      <div className="bg-gray-800 p-6 text-center text-white">
        <p className="mb-2">Keep up the great work caring for {data.petName}! 🐾</p>
        <p className="text-sm opacity-75">
          This report was generated by PawPal AI Assistant
        </p>
      </div>
    </div>
  );
};

// Generate HTML email string for sending
export const generateWeeklyHealthReportHTML = (data: WeeklyHealthReportData): string => {
  // This would generate the actual HTML email string
  // For now, returning a placeholder
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Weekly Health Report - ${data.petName}</title>
</head>
<body>
  <!-- Email content would be rendered here -->
</body>
</html>`;
};
